services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - "8080:8080" 