services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8080:8080" 